### ISSUE TITLE
How to load a theme in README

### ISSUE THREAD

**Issue by Nyoho** [conao3/iceberg-theme.el#1]
`(load-theme "solarized-iceberg-dark" t)` がエラーになって、`(load-theme 'solarized-iceberg-dark t)` だと通るんですが環境の問題でしょうか。

**Comment by conao3** [comment]
すいません、間違えていました! 報告ありがとうございます!

**Comment by conao3** [comment]
https://github.com/conao3/iceberg-theme.el/commit/9615307cbd37e698d6939a04128162ef893313cb

**Comment by Nyoho** [comment]
LGTM!
