### ISSUE TITLE
Should I inogre a file generated by iceberg-theme-create-theme-file?

### ISSUE THREAD

**Issue by Nyoho** [conao3/iceberg-theme.el#2]
```emacs-lisp
  (leaf iceberg-theme
    :ensure t
    :config
    (iceberg-theme-create-theme-file)
    (load-theme 'solarized-iceberg-dark t))
```
として使うと ~/.emacs.d/themes` に solarized-iceberg-dark-theme.el が生成されるんですが、これはベストプラクティスとしては、一旦生成したものは Git 管理するものなんでしょうか。それとも themes/ は gitignore するものなんでしょうか。

**Comment by conao3** [comment]
themesはgitignoreするものですね。
もしこちらで書き換えた場合、ローカルに残っているとずっと古いテーマファイルをロードし続けてしまうので

**Comment by Nyoho** [comment]
ありがとうございます。光の速さでgitignoreしたいと思います!

**Comment by conao3** [comment]
いえいえ。
別途、フェイスが見辛い等ありましたら報告頂ければと思います。
自分では使ってないので、不便さは気付けないので。。
